### ISSUE TITLE
关于asdb超链接

### ISSUE THREAD

**Issue by ZocP** [hope-meeter/ZjuFrontEnd#1]
ASDB超链接为asdb.live。原超链接我们正在修复中捏
一个魂们辛苦了

**Comment by hope-meeter** [comment]
收到，稍后将更新。
请问您是ASDB的开发者吗？能否将本站（枝江大学：https://zhijiang.university/）加入友情链接呢？
谢谢。

**Comment by ZocP** [comment]
开发者：
你好！
我是ASF企划的项目负责人。我们的网站是asoulfan.com。关于asdb，目前asdb的服务托管在我们的服务器上，域名解析问题暂未修复。asdb超链接为https://livedb.asoulfan.com/gitweb/index.html因为解析暂时出了些状况，默认80无法使用暂时方案是asdb.live301到原超链接。
ZocP
ProjectASF


------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Tuesday, Sep 21, 2021 11:17 AM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [hope-meeter/ZjuFrontEnd] 关于asdb超链接 (#1)





 
收到，稍后将更新。
 请问您是ASDB的开发者吗？能否将本站（枝江大学：https://zhijiang.university/）加入友情链接呢？
 谢谢。
