### ISSUE TITLE
疑似数据丢失，原有提交的校友记录如今无法被搜索到

### ISSUE THREAD

**Issue by WendaoLee** [hope-meeter/ZjuFrontEnd#2]
校友名单上我记得我本人曾在建站时提交过自己的校友记录，但是今天点开网站好奇搜索时未找到自己的提交记录。
当时学号大概是100左右，id是李问道。
印象里我在十月末还搜索到过来着。

**Comment by hope-meeter** [comment]
您好，感谢关注。
这是近期对服务器进行了数据分页，但没有更新网站的原因。
您可暂时微信搜索"枝江网络降重"使用校友会功能，本项目网站将在近期更新。

**Comment by WendaoLee** [comment]
> 您好，感谢关注。
> 这是近期对服务器进行了数据分页，但没有更新网站的原因。
> 您可暂时微信搜索微信小程序"枝江网络降重"使用校友会功能，本项目网站将在近期更新。

好的了解。加油。
